[package]
name = "p2p-share"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "fs"] }
clap = { version = "4.5.48", features = ["derive"] }
serde = { version = "1.0.226", features = ["derive"] }
postcard = "1.1.3" # or bincode
blake3 = "1.8.2"
indicatif = "0.18.0"
anyhow = "1.0.100"

libp2p = { version = "0.56.0", default-features = false, features = [
  "tcp","quic","noise","yamux",
  "mdns","identify","kad","autonat","relay","dcutr",
  "request-response"
] }

serde_json = "1.0"
rand = "0.9.2"
base64 = "0.22.1"
petname = "2.0.2"
qrcodegen = "1.8.0"