[package]
name = "p2p-share"
version = "0.2.0"
edition.workspace = true
description = "A simple P2P file sharing tool"

[dependencies]
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
p2p-share-core = { path = "../core" }
